name = "instacaption"
compatibility_date = "2025-06-27"

[build]
command = "npx @cloudflare/next-on-pages"

[site]
bucket = ".vercel/output/static"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
